'use client';

import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import { Place } from '@/components/lead-profile-audit';

const styles = StyleSheet.create({
  page: { padding: 30, fontSize: 12 },
  section: { marginBottom: 12 },
  heading: { fontSize: 16, marginBottom: 10 },
  item: { marginBottom: 4 },
});

export function LeadAuditPDF({ lead }: { lead: Place }) {
  return (
    <Document>
      <Page style={styles.page}>
        <View style={styles.section}>
          <Text style={styles.heading}>Business Profile Audit</Text>
          <Text style={styles.item}>Name: {lead.name}</Text>
          <Text style={styles.item}>Address: {lead.address}</Text>
          <Text style={styles.item}>
            Phone: {lead.formatted_phone_number || 'N/A'}
          </Text>
          <Text style={styles.item}>Website: {lead.website || 'N/A'}</Text>
          <Text style={styles.item}>Rating: {lead.rating ?? 'N/A'}</Text>
          <Text style={styles.item}>
            Total Reviews: {lead.user_ratings_total ?? 0}
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.heading}>Audit Checklist</Text>
          <Text style={styles.item}>
            Has Website: {lead.website ? 'Yes' : 'No'}
          </Text>
          <Text style={styles.item}>
            Has Phone Number: {lead.formatted_phone_number ? 'Yes' : 'No'}
          </Text>
          <Text style={styles.item}>
            Has Business Hours:{' '}
            {lead.opening_hours?.weekday_text?.length ? 'Yes' : 'No'}
          </Text>
          <Text style={styles.item}>
            Has Valid Photos:{' '}
            {Array.isArray(lead.photos) && lead.photos.length > 0
              ? 'Yes'
              : 'No'}
          </Text>
          <Text style={styles.item}>
            Has Categories:{' '}
            {Array.isArray(lead.types) && lead.types.length > 0 ? 'Yes' : 'No'}
          </Text>
          <Text style={styles.item}>
            ≥ 10 Reviews: {(lead.user_ratings_total ?? 0) >= 10 ? 'Yes' : 'No'}
          </Text>
          <Text style={styles.item}>
            Rating ≥ 4.0: {(lead.rating ?? 0) >= 4.0 ? 'Yes' : 'No'}
          </Text>
        </View>

        <Text style={{ fontSize: 10, marginTop: 20 }}>
          Generated by Your App | https://yourapp.com
        </Text>
      </Page>
    </Document>
  );
}
