import { Separator } from '@/components/ui/separator';

export default function PrivacyPolicyPage() {
  return (
    <main className='max-w-4xl mx-auto px-6 py-20'>
      <h1 className='text-4xl font-bold mb-6'>Privacy Policy</h1>
      <p className='text-muted-foreground mb-6'>Effective Date: May 3, 2025</p>

      <div className='space-y-6 text-sm leading-6 text-muted-foreground'>
        <p>
          WebbedLeads (“we”, “us”, or “our”) is committed to protecting your
          privacy. This Privacy Policy explains how we collect, use, disclose,
          and safeguard your information when you use our website and platform.
          By using WebbedLeads, you agree to the collection and use of
          information in accordance with this policy.
        </p>

        <Separator className='my-4' />

        <h2 className='text-lg font-semibold'>1. Information We Collect</h2>
        <p>We collect the following types of data:</p>
        <ul className='list-inside space-y-1'>
          <li className='mb-4'>
            <strong>1.1 Personal Information</strong>
            <ul className='list-disc list-inside space-y-1'>
              <li className='pl-4'>Name</li>
              <li className='pl-4'>Email address</li>
              <li className='pl-4'>Company or team name</li>
              <li className='pl-4'>
                Payment details (handled securely by Stripe)
              </li>
              <li className='pl-4'>IP address</li>
            </ul>
          </li>
          <li className='mb-4'>
            <strong>1.2 Business Data</strong>
            <ul className='list-disc list-inside space-y-1'>
              <li className='pl-4'>
                Lead profile details (Google Business Profile information,
                including business name, address, hours, reviews, etc.)
              </li>
              <li className='pl-4'>
                Website data and metadata (scraped via Puppeteer)
              </li>
              <li className='pl-4'>Audit content generated by AI (OpenAI)</li>
              <li className='pl-4'>Lead scoring metrics</li>
              <li className='pl-4'>
                User activity (status updates, assignments, notes)
              </li>
            </ul>
          </li>
          <li>
            <strong>1.3 Technical Data</strong>
            <ul className='list-disc list-inside space-y-1'>
              <li className='pl-4'>Browser type, operating system, device</li>
              <li className='pl-4'>Log data and usage analytics</li>
            </ul>
          </li>
        </ul>

        <Separator className='my-4' />

        <h2 className='text-lg font-semibold'>
          2. How We Use Your Information
        </h2>
        <p>We use your data to:</p>
        <ul className='pl-4 list-disc list-inside space-y-1'>
          <li>Provide and operate the WebbedLeads platform</li>
          <li>Perform website audits and lead scoring using AI</li>
          <li>Enhance the quality of lead recommendations</li>
          <li>Track usage for product improvement</li>
          <li>
            Send product updates, newsletters, and promotional content (only if
            you consent)
          </li>
          <li>Process billing and subscription management (via Stripe)</li>
          <li>Comply with legal obligations</li>
        </ul>

        <Separator className='my-4' />

        <h2 className='text-lg font-semibold'>3. Email Marketing</h2>
        <p>
          If you opt-in during sign-up, we may send marketing emails via
          Mailchimp. You may unsubscribe at any time via a link in any email.
        </p>
        <div className='pl-4 my-6 border-l border-white'>
          <strong>
            You will not be added to our mailing list unless you check the
            consent box during signup.
          </strong>
        </div>

        <Separator className='my-4' />

        <h2 className='text-lg font-semibold'>
          4. Sharing of Your Information
        </h2>
        <p>
          We do not sell your personal data. We may share data with the
          following service providers solely to operate our platform:
        </p>

        <h2 className='text-lg font-semibold'>5. Cookies & Tracking</h2>
        <p>
          We use cookies to track usage and preferences. You can control cookies
          through your browser settings.
        </p>

        <h2 className='text-lg font-semibold'>6. Your Rights</h2>
        <p>
          You may request access to or deletion of your personal data at any
          time by contacting us at support@webbedleads.com.
        </p>

        <h2 className='text-lg font-semibold'>7. Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy. Changes will be posted on this page
          with an updated effective date.
        </p>

        <h2 className='text-lg font-semibold'>8. Contact</h2>
        <p>
          For any questions or privacy-related requests, please contact us at:{' '}
          <a className='underline' href='mailto:support@webbedleads.com'>
            support@webbedleads.com
          </a>
        </p>
      </div>
    </main>
  );
}
