import { Separator } from '@/components/ui/separator';

export default function PrivacyPolicyPage() {
  return (
    <main className='max-w-4xl mx-auto px-6 py-20'>
      <h1 className='text-4xl font-bold mb-6'>Privacy Policy</h1>
      <p className='text-muted-foreground mb-6'>Effective Date: May 3, 2025</p>

      <div className='space-y-6 text-sm leading-6 text-muted-foreground'>
        <p>
          WebbedLeads (“we”, “us”, or “our”) is committed to protecting your
          privacy. This Privacy Policy explains how we collect, use, disclose,
          and safeguard your information when you use our website and platform.
          By using WebbedLeads, you agree to the collection and use of
          information in accordance with this policy.
        </p>

        <Separator className='my-4' />

        <h2 className='text-lg font-semibold'>1. Information We Collect</h2>
        <p>We collect the following types of data:</p>
        <ul className='list-inside space-y-1'>
          <li className='mb-4'>
            <strong>1.1 Personal Information</strong>
            <ul className='list-disc list-inside space-y-1'>
              <li className='pl-4'>Name</li>
              <li className='pl-4'>Email address</li>
              <li className='pl-4'>Company or team name</li>
              <li className='pl-4'>
                Payment details (handled securely by Stripe)
              </li>
              <li className='pl-4'>IP address</li>
            </ul>
          </li>
          <li className='mb-4'>
            <strong>1.2 Business Data</strong>
            <ul className='list-disc list-inside space-y-1'>
              <li className='pl-4'>
                Lead profile details (Google Business Profile information,
                including business name, address, hours, reviews, etc.)
              </li>
              <li className='pl-4'>
                Website data and metadata (scraped via Puppeteer)
              </li>
              <li className='pl-4'>Audit content generated by AI (OpenAI)</li>
              <li className='pl-4'>Lead scoring metrics</li>
              <li className='pl-4'>
                User activity (status updates, assignments, notes)
              </li>
            </ul>
          </li>
          <li>
            <strong>1.3 Technical Data</strong>
            <ul className='list-disc list-inside space-y-1'>
              <li className='pl-4'>Browser type, operating system, device</li>
              <li className='pl-4'>Log data and usage analytics</li>
            </ul>
          </li>
        </ul>

        <Separator className='my-4' />

        <h2 className='text-lg font-semibold'>
          2. How We Use Your Information
        </h2>
        <p>We use your data to:</p>
        <ul className='pl-4 list-disc list-inside space-y-1'>
          <li>Provide and operate the WebbedLeads platform</li>
          <li>Perform website audits and lead scoring using AI</li>
          <li>Enhance the quality of lead recommendations</li>
          <li>Track usage for product improvement</li>
          <li>
            Send product updates, newsletters, and promotional content (only if
            you consent)
          </li>
          <li>Process billing and subscription management (via Stripe)</li>
          <li>Comply with legal obligations</li>
        </ul>

        <Separator className='my-4' />

        <h2 className='text-lg font-semibold'>3. Email Marketing</h2>
        <p>
          If you opt-in during sign-up, we may send marketing emails via
          Mailchimp. You may unsubscribe at any time via a link in any email.
        </p>
        <div className='pl-4 my-6 border-l border-white'>
          <strong>
            You will not be added to our mailing list unless you check the
            consent box during signup.
          </strong>
        </div>

        <Separator className='my-4' />

        <h2 className='text-lg font-semibold'>
          4. Sharing of Your Information
        </h2>
        <p>
          We do not sell your personal data. We may share data with the
          following service providers solely to operate our platform:
        </p>

        <ul className='pl-4 list-disc list-inside space-y-1'>
          <li>
            <strong> Supabase</strong> – Authentication, database, storage
          </li>
          <li>
            <strong> OpenAI</strong> – AI-powered website analysis
          </li>
          <li>
            <strong> Google Places API & Maps</strong> – Lead enrichment
          </li>
          <li>
            <strong> Stripe</strong> – Secure billing and subscription
            processing
          </li>
          <li>
            <strong> Mailchimp </strong>– Email newsletter and updates
          </li>
          <li>
            <strong> Render</strong> – Web scraping backend infrastructure
          </li>
        </ul>
        <p>
          All partners are bound by strict confidentiality and data protection
          agreements.
        </p>

        <Separator className='my-4' />

        <h2 className='text-lg font-semibold'>5. Data Retention</h2>
        <p>
          We retain your data as long as your account is active, or as needed to
          provide you services. You may request deletion of your data by
          contacting us at{' '}
          <span className='text-primary'> support@webbedleads.com</span>.
        </p>

        <Separator className='my-4' />

        <h2 className='text-lg font-semibold'>6. Your Rights</h2>
        <p>You have the right to:</p>
        <ul className='pl-4 list-disc list-inside space-y-1'>
          <li>Access or correct your data</li>
          <li>Request deletion of your account</li>
          <li>Withdraw marketing consent at any time</li>
          <li>File a complaint with your local privacy authority</li>
        </ul>
        <p>
          To exercise your rights, email:{' '}
          <span className='text-primary'> support@webbedleads.com</span>.
        </p>

        <Separator className='my-4' />

        <h2 className='text-lg font-semibold'>7. Cookies & Tracking</h2>
        <p>We use cookies to:</p>
        <ul className='pl-4 list-disc list-inside space-y-1'>
          <li>Keep you logged in</li>
          <li>Store preferences</li>
          <li>
            Analyze product usage (e.g., via Plausible or other privacy-focused
            analytics)
          </li>
        </ul>
        <p>You may disable cookies via your browser settings.</p>

        <h2 className='text-lg font-semibold'>8. Security</h2>
        <p>
          We take data protection seriously and implement industry-standard
          encryption and security practices to protect your data.
        </p>

        <Separator className='my-4' />

        <h2 className='text-lg font-semibold'>9. Children&apos;s Privacy</h2>
        <p>
          WebbedLeads is not intended for use by anyone under 18. We do not
          knowingly collect personal information from children.
        </p>

        <Separator className='my-4' />

        <h2 className='text-lg font-semibold'>10. Changes to This Policy</h2>
        <p>
          We may update this policy from time to time. The latest version will
          always be posted on this page. We will notify you of significant
          changes via email or within the platform.
        </p>

        <Separator className='my-4' />
        <h2 className='text-lg font-semibold'>11. Contact Us</h2>
        <p>
          If you have questions about this Privacy Policy, contact us at:
          <br /> Email:{' '}
          <span className='text-primary'> privacy@webbedleads.com</span>
        </p>
      </div>
    </main>
  );
}
